### ISSUE TITLE
URLError: <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by Asterrea** [ustroetz/python-osrm#8]
I exactly need this wrapper to use OSRM. I installed it however, as I run my own little test script:

```
import osrm

points= [(120.9834301, 14.60350785), (120.9924853, 14.60077731), (121.005038,14.60173248),
         (121.017, 14.6042), (121.026, 14.6105), (121.034, 14.6136),(121.043, 14.6185),
         (121.053, 14.6227), (121.065, 14.628), (121.073, 14.631), (121.086, 14.6223)]

result= osrm.match(points, overview="simplified")

print(result)
```

The following error occurs at urlopen:

```
['http://localhost:5000', '/match/', 'v1', '/', 'driving', '/', 
'120.9834301,14.60350785;120.9924853,14.60077731;121.005038,14.60173248;121.017,
14.6042;121.026,14.6105;121.034,14.6136;121.043,14.6185;121.053,14.6227;121.065,
14.628;121.073,14.631;121.086,14.6223', 
'?overview=simplified&steps=false&geometries=polyline']

Traceback (most recent call last):
  File "/home/gridlockdev/Desktop/pythonidle/GTFS-GEOJSON/test-gjson2shp/osrm-test.py", line 7, in <module>
    result= osrm.match(points, overview="simplified")
  File "build/bdist.linux-x86_64/egg/osrm/core.py", line 83, in match
    r = urlopen("".join(url))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
```

How can I resolve this?

**Comment by gisxperts** [comment]
The issue is your osrm instance
 Do you have osrm running at localhost at port 5000 as suggested from your output.  Can you test in a browser first http://localhost:5000/match

-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 20.09.17, 02:42, Theresa <notifications@github.com> schrieb:
I exactly need this wrapper to use OSRM. I installed it however, as I run my own little test script:
`import osrm
points= [(120.9834301, 14.60350785), (120.9924853, 14.60077731), (121.005038,14.60173248),
(121.017, 14.6042), (121.026, 14.6105), (121.034, 14.6136),(121.043, 14.6185),
(121.053, 14.6227), (121.065, 14.628), (121.073, 14.631), (121.086, 14.6223)]
result= osrm.match(points, overview="simplified")
print(result)
`
The following error occurs at urlopen:
`['http://localhost:5000', '/match/', 'v1', '/', 'driving', '/', '120.9834301,14.60350785;120.9924853,14.60077731;121.005038,14.60173248;121.017,14.6042;121.026,14.6105;121.034,14.6136;121.043,14.6185;121.053,14.6227;121.065,14.628;121.073,14.631;121.086,14.6223', '?overview=simplified&steps=false&geometries=polyline']
Traceback (most recent call last):
File "/home/gridlockdev/Desktop/pythonidle/GTFS-GEOJSON/test-gjson2shp/osrm-test.py", line 7, in 
result= osrm.match(points, overview="simplified")
File "build/bdist.linux-x86_64/egg/osrm/core.py", line 83, in match
r = urlopen("".join(url))
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 429, in open
response = self._open(req, data)
File "/usr/lib/python2.7/urllib2.py", line 447, in _open
'_open', req)
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
return self.do_open(httplib.HTTPConnection, req)
File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>`
How can I resolve this?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ustroetz/python-osrm","title":"ustroetz/python-osrm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ustroetz/python-osrm"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"URLError: \u003curlopen error [Errno 111] Connection refused\u003e (#8)"}],"action":{"name":"View Issue","url":"https://github.com/ustroetz/python-osrm/issues/8"}}}

**Comment by Asterrea** [comment]
I see. I made a workaround on it pointing the url to http://router.project-osrm.org/[query]. I actually did not understand why the url is pointing at localhost:5000? Sorry a newb in GIS projects.
